// @ts-nocheck

import Footer from '$COMPONENTS-ALIAS/footer';
import Navbar from '$COMPONENTS-ALIAS/navbar';
import Toaster from '$COMPONENTS-ALIAS/toaster';
import { getJsonData } from '$LIB-ALIAS/get-json-data';
import { getStructureInstance } from '$LIB-ALIAS/structure';
import { cn } from '$LIB-ALIAS/utils';
import { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Doxium app',
    description: 'New doxium app generated by create-doxium-app',
};

const RootLayout = async ({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) => {
    const { socials } = await getJsonData();
    const structure = await getStructureInstance();
    return (
        <html lang='en' className={cn('dark antialiased', inter.className)}>
            <body className='relative'>
                <main>
                    <Navbar structure={structure} socials={socials} />
                    {children}
                    <Footer />
                    <Toaster />
                </main>
            </body>
        </html>
    );
};

export default RootLayout;
