// @ts-nocheck

import DocsToaster from '$COMPONENTS-ALIAS/docs-toaster';
import Navbar from '$COMPONENTS-ALIAS/navbar';
import { getStructureInstance } from '$LIB-ALIAS/structure';
import { cn } from '$LIB-ALIAS/utils';
import { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Doxium app',
    description: 'New doxium app generated by create-doxium-app',
};

const RootLayout = async ({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) => {
    const structure = await getStructureInstance();
    return (
        <html lang='en' className={cn('dark antialiased', inter.className)}>
            <body className='relative'>
                <Navbar structure={structure} />
                <main>
                    {children}
                    <DocsToaster />
                </main>
            </body>
        </html>
    );
};

export default RootLayout;
