// @ts-nocheck

import { Navbar } from '$COMPONENTS-ALIAS/navbar';
import { cn } from '$LIB-ALIAS/utils';
import { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Toaster } from 'sonner';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Doxium app',
    description: 'New doxium app generated by create-doxium-app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en' className={cn('dark antialiased', inter.className)}>
            <body className='relative'>
                <Navbar />
                <main>
                    {children}
                    <Toaster richColors theme='dark' />
                </main>
            </body>
        </html>
    );
}
