// @ts-nocheck

import DocsBreadcrumbs from '$COMPONENTS-ALIAS/docs-breadcrumbs';
import DocsNav from '$COMPONENTS-ALIAS/docs-nav';
import SecondarySidebar from '$COMPONENTS-ALIAS/docs-secondary-sidebar';
import Sidebar from '$COMPONENTS-ALIAS/docs-sidebar';
import DocsToaster from '$COMPONENTS-ALIAS/docs-toaster';
import Navbar from '$COMPONENTS-ALIAS/navbar';
import { getRepoLink } from '$LIB-ALIAS/get-repo-link';
import { cn } from '$LIB-ALIAS/utils';
import { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Doxium app',
    description: 'New doxium app generated by create-doxium-app',
};

const RootLayout = async ({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) => {
    const repoString = await getRepoLink();
    return (
        <html lang='en' className={cn('dark antialiased', inter.className)}>
            <body className='relative '>
                <Navbar />
                <main>
                    <div className='relative flex flex-row justify-center space-x-8 py-24'>
                        <Sidebar />
                        <div className='prose prose-$COLOR prose-invert prose-p:my-4 prose-headings:my-2 prose-headings:mt-4 prose-headings:w-full prose-headings:border-b prose-headings:border-white/15 prose-ul:mb-4 prose-ol:mb-4 prose-headings:pb-1.5 prose-a:decoration-dotted hover:prose-a:text-$ACCENT-COLOR-500 prose-ol:my-0 prose-ul:my-0 prose-hr:border-white/20 flex h-fit w-screen flex-shrink-0 flex-col items-start lg:max-w-[40%] lg:px-0'>
                            <DocsBreadcrumbs />
                            {children}
                            <div className='mb-4 mt-8 h-[1px] w-full bg-white/15' />
                            <DocsNav />
                        </div>
                        <SecondarySidebar repoString={repoString} />
                    </div>
                    <DocsToaster />
                </main>
            </body>
        </html>
    );
};

export default RootLayout;
