// @ts-nocheck

import config from 'config';
import { Footer } from 'doxium/components/footer';
import { Navbar } from 'doxium/components/navbar';
import { Sidebar } from 'doxium/components/sidebar-filetree';
import { Toaster } from 'doxium/components/toaster';
import { getDocsTree } from 'doxium/lib';
import { cn } from 'doxium/utils';
import { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });
const colorScheme = config.style.colorScheme;
const appName = config.misc.appName;
const appDescription = config.misc.appDescription;

export const metadata: Metadata = {
    title: appName ?? 'Doxium app',
    description: appDescription ?? 'New doxium app generated by @doxium/cli',
};

const RootLayout = async ({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) => {
    const tree = await getDocsTree();
    return (
        <html lang='en' className={cn('antialiased', inter.className, colorScheme === 'dark' ? 'dark' : 'light')}>
            <body className='relative'>
                <main>
                    <Navbar tree={tree} />
                    <div className='relative flex min-h-screen flex-row justify-center gap-8 pb-2 pt-16 lg:pt-24'>
                        <Sidebar tree={tree} />
                        {children}
                    </div>
                    <Footer />
                    <Toaster />
                </main>
            </body>
        </html>
    );
};

export default RootLayout;
